# Generated by Django 2.2.3 on 2021-05-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakeasyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date posted')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('video', models.FileField(upload_to='videos/')),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date posted')),
            ],
        ),
    ]
