# Generated by Django 2.2.3 on 2021-05-27 20:54

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('speakeasyApp', '0003_auto_20210517_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_manufacture', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('video', s3direct.fields.S3DirectField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'videos',
                'verbose_name': 'video',
            },
        ),
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
