# Generated by Django 2.2.3 on 2021-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakeasyApp', '0007_customuser_subscription_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter_users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date posted')),
            ],
        ),
    ]
