# Generated by Django 2.2.3 on 2021-07-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakeasyApp', '0009_auto_20210621_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stripeCustomerId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stripeSubscriptionId',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
